name: Node.js CI

on:
  push:
    branches: [ "master"]

jobs:
  build:
    environment: ${{ github.ref_name }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: npm run build 

      - name: Archive build artifacts
        run: tar -czf build-artifacts.tar.gz dist
        shell: bash

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: build-artifacts.tar.gz

  run:
    environment: ${{ github.ref_name }}
    runs-on: self-hosted
    needs: build
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: build-artifacts
          path: ./build

      - name: Extract build artifacts
        run: tar -xzf ./build/build-artifacts.tar.gz -C ./build
        shell: bash

      - name: Run Node.js application
        run: npx tsx ./build/dist/app.js
        shell: bash
